dist: xenial
sudo: required
services:
- docker
language: go
go:
- 1.15.x
script:
# tests require XOA server so hold off on that for now  - make test
- make build
before_deploy:
- make dist
deploy:
  provider: releases
  api_key:
    secure: V8Ow00cSBVK3pPYfkEMG366B2JkwAKxvIAEi0VgzwbFmngYiYp0moJr3nu6b1h18aapcNK1zQb+DHJxIICue+0iTiBTb3npbxnyprkGvKx8aVY04fWET611t7094xY2in2beD1u6U9gOvShVrqWXfBpx6vMfMgnunzV854YMrRtm8I/1zBTkfgrDlCsYswNp5jwYaNJ0naAo35zbl598zOPt/Bg55Nz1G7jY9QL03iMoL3pZDjqraBBsPBc7jkYggYmX2EqwrWuXjVqIAEnXKc1JtN6/2Ix/Q/RJ3sn3LbMFm0R1Y61gxYvns8hzk75G26LWUTacDaZVAIZorXLa9YVVmNFXKfLpQzpK0rONTr52Sz25pjz62K/IZwMSJzmGOh5QzkuGkkzbu2NfH+dTgDY4x4xQ+4RRkPOPP/zTtysn7kEFJ3cKXgxTYhBvYwbB1mj0QOmkFP2iX+yqO/3f12ykT3mYK/hWEL/39IRFxWLPYd/mFAZXYAjH/HRNNgouvdc1HrGd15/vArr5sowcvKQEDxHcaKR4nepuWebirzI+nqEurexHJ87FS+2n0iQetpedl5tglHBgGStUhx1AXpRMZId7Yba/eTOIciE+SpvFxOHGKUORCU5kj4D5E/8VsbsjdI41v33Mli2ibLgY266xgVpHn2NN+aE30WhgKlY=
  file: dist/terraform-provider-xenorchestra*
  file_glob: true
  skip_cleanup: true
  on:
    repo: terra-farm/terraform-provider-xenorchestra
    tags: true
